### ISSUE TITLE
boj5397 - 키로거

### ISSUE THREAD

**Issue by newmki** [newmki/algorithm#49]
https://www.acmicpc.net/problem/5397

**Comment by 42-mki** [comment]
2021-12-24

문제 분석: 2분
자료 구조: List

# 알고리즘
1. < > - 가 아니라면 List에 Insert하고, Index를 ++한다.
2. < 라면 index를 --하고, > 라면 index를 ++ 한다. index 이동은 0 ~ list.length
3. - 라면 List에서 Index위치 값을 Delete한다.
4. Input의 끝까지 1 ~ 3 반복
5. 반복이 끝나면 결과를 출력한다.

**Comment by newmki** [comment]
계속해서 틀렸었는데, 알고보니 테스트케이스마다 개행을 안 넣어주어서 그랬다...
